name: flutter_login_challenge
description: "Project to satisfy the challenge of the interview process of the company"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  dio: ^5.4.0

  flutter_svg_provider: ^1.0.7
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  bloc_test: ^9.1.5
  mocktail: ^1.0.3
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
