// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2gIAiLQdnykznpPKgH2X7zH75CUi8KU',
    appId: '1:408801416316:web:ad5791df3d5c575391e5f9',
    messagingSenderId: '408801416316',
    projectId: 'flutter-login-challenge',
    authDomain: 'flutter-login-challenge.firebaseapp.com',
    storageBucket: 'flutter-login-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmI0sLTRvrQVSPCdlIxAPFi2uUltDwbDU',
    appId: '1:408801416316:android:4923c94204f58a7191e5f9',
    messagingSenderId: '408801416316',
    projectId: 'flutter-login-challenge',
    storageBucket: 'flutter-login-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKqDJlm8MuctAwvwLDq3TmyWVbdu5xnzc',
    appId: '1:408801416316:ios:f1c54a019cfbd42191e5f9',
    messagingSenderId: '408801416316',
    projectId: 'flutter-login-challenge',
    storageBucket: 'flutter-login-challenge.appspot.com',
    iosBundleId: 'dev.walicen.flutterLoginChallenge',
  );
}
